
# defaultProject: rapsodo-basketball-444807
# defaultLocation: US
# defaultDataset: dataform
# defaultAssertionDataset: dataform_assertions
# dataformCoreVersion: 3.0.0


defaultProject: bigquery-public-data
defaultLocation: US
defaultDataset: ncaa_basketball

defaultProject: rapsodo-basketball-444807
defaultLocation: us-west1
#defaultSchema: dataform
defaultDataset: dataform

defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0
